name: Deploy to Production

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd ~/TIS/DevOps
            git checkout dev
            git pull origin dev
            docker compose pull
            docker compose up -d
            # Running Laravel migrations
            docker exec megabyte-backend php artisan migrate:rollback
            docker exec megabyte-backend php artisan migrate:fresh --seed
